### ISSUE TITLE
请问viewer中展示的时候为什么要交换坐标轴？

### ISSUE THREAD

**Issue by hanxuanhuo** [TomseYang666/pylvxreader#1]
point_list.append([x1, y1, z1])
point_list.append([x2, y2, z2])
area_point_list.append([y1, -z1, -x1])
area_point_list.append([y2, -z2, -x2])
这个地方为什么要把点的坐标交换？

**Comment by TomseYang666** [comment]
这个地方是因为我用的雷达和GNSS芯片放置位置的问题，没记错的话是因为雷达是倒过来用的，所以转换到正常的坐标轴的时候需要做一个坐标轴转换，我记得是这样的，如果没解决问题我再去查一下详细的说明文档。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TomseYang666/pyLivox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月11日(星期六) 下午2:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[TomseYang666/pyLivox] 请问viewer中展示的时候为什么要交换坐标轴？ (Issue #1)





 
point_list.append([x1, y1, z1])
 point_list.append([x2, y2, z2])
 area_point_list.append([y1, -z1, -x1])
 area_point_list.append([y2, -z2, -x2])
 这个地方为什么要把点的坐标交换？

**Comment by TomseYang666** [comment]
所以有解决你的问题嘛

**Comment by hanxuanhuo** [comment]
> 
我明白你的解释了。可能不同的雷达有区别吧，我按你的方法旋转后位置反而和坐标轴对齐了。问题我先关了，谢谢。
